### ISSUE TITLE
Any plans to release 2.13.0 to maven in the near future ?

### ISSUE THREAD

**Issue by sheinbergon** [jurmous/etcd4j#123]
2.12.0 is not really usable due to the whole netty version issue mentioned in #116 
Watches also don't work in that version, again due to the same issue.

**Comment by lburgazzoli** [comment]
@jurmous what do you think ?

**Comment by sheinbergon** [comment]
@lburgazzoli  @jurmous  ? What do you say ?

**Comment by sheinbergon** [comment]
@lburgazzoli  @jurmous  any news on this ?

**Comment by lburgazzoli** [comment]
@jurmous any chance we cut a release soon ?

**Comment by jurmous** [comment]
Sorry for the late reply. It has been a difficult month.... 

I cannot release because a test fails on my machine. See #131.

I published a SNAPSHOT release though of master.

**Comment by sheinbergon** [comment]
@jurmous it's a shame , new comers to your sdk will probably use the latest non-SNAPSHOT version 2.12.0 which is not working in some scenarios. Maybe at least change the front page to use 2.11.0 or remove it from maven central...

**Comment by sheinbergon** [comment]
@jurmous @lburgazzoli any response ?

**Comment by lburgazzoli** [comment]
There is an issue #131 which unfortunately I'm not able to reproduce, any help would be appreciated.

**Comment by jurmous** [comment]
I am unfortunately very distracted with lately multiple things happening... @lburgazzoli I now want to give you access to publish because it seems I don't have the proper time and attention. 

Can you email me at jurmous@jurmo.us with your ossrh username. Afterwards confirm your identity by posting here a keyword you used in your email with your username.
http://central.sonatype.org/pages/ossrh-guide.html

Then I will open an issue to grant you access for publishing. (Takes possibly some days) If you have questions on the setup that is not answered with the guide, please email me.

**Comment by sheinbergon** [comment]
@jurmous  thanks for responding ,I appreciate your hard work and effort put into making etcd4j a reality

**Comment by lburgazzoli** [comment]
See #131
