### ISSUE TITLE
testHealth hangs in TestFunctionality

### ISSUE THREAD

**Issue by jurmous** [jurmous/etcd4j#131]
Run testHealth in TestFunctionality and it hangs with etcd 3.0.13 and 2.3.7.

**Comment by lburgazzoli** [comment]
Any specific thing to do? because it does not hang for me

**Comment by sheinbergon** [comment]
@jurmous  anything I can do to help ?

**Comment by sheinbergon** [comment]
@jurmous  @lburgazzoli  which branch should I test against

**Comment by lburgazzoli** [comment]
master

**Comment by sheinbergon** [comment]
@jurmous  @lburgazzoli  I've tested locally on both etcd 2.3.7 with 3.0.13 ( downloaded from cores etcd github repo )  and couldn't reproduce either. All tests have passed for both cases

I'm testing using Netbeans ( gradle daemon version is 3.1 from what I see )
Go Lang version is 1.6.3
JDK version is 1.8.0_111
OS version is Xubuntu 16.04 LTS

Looking at the testHealth and judging by the symptoms, it's sounds kind of similar to what happens in 2.12.0 and that's due to bad netty version/behavior. Which is weird, because the netty version has been upgraded. 

@jurmous are you able to constantly reproduce the issue ?

**Comment by idans-ybrantdigital-com** [comment]
@jurmous  @lburgazzoli  what gives ?

**Comment by sheinbergon** [comment]
@lburgazzoli @jurmous  what's going on? I understand you're busy and everything, but why aren't you at least responding ?

**Comment by lburgazzoli** [comment]
@sheinbergon I do not know what is taking @jurmous away from the project but he should have some valid reason so be patient.

I can't release new versions, this is something in @jurmous hands so again be patient.

**Comment by idans-ybrantdigital-com** [comment]
@lburgazzoli  OK thanks for responding

**Comment by sheinbergon** [comment]
@lburgazzoli  OK, thanks for responding

**Comment by lburgazzoli** [comment]
@sheinbergon I've pushed a new snapshot with the latest dependencies and moved reconnection to use Netty's event loop instead of a timer, any test would be really helpful.

**Comment by sheinbergon** [comment]
@lburgazzoli  thanks. I didn't get it. Do you want me to test the SDK or write a test scenario myself?

**Comment by lburgazzoli** [comment]
Just test if it works as expected in your application, looking for regressions.
If you have time and want to submit a PR with a test case for re-connection, it would be really appreciated.

**Comment by sheinbergon** [comment]
Could you please point to your changes/specific commits ?

**Comment by lburgazzoli** [comment]
https://github.com/jurmous/etcd4j/commit/b842194a1bee2d0700cc5f814453ebc6b1301431

**Comment by sheinbergon** [comment]
@lburgazzoli  OK. I'll try and have a look next week

**Comment by lburgazzoli** [comment]
@sheinbergon have you had any time to check it ?

**Comment by lburgazzoli** [comment]
etcd4j 2.13.0 has been released, should be available soon on maven central
