### ISSUE TITLE
EtcdException to have constructor accepting string value

### ISSUE THREAD

**Issue by ghristov** [jurmous/etcd4j#28]
For example I want to throw custom EtcdException and I can't. Other reason is that i handle IOException, TimeoutException and I want to throw new EtcdException with custom error message. Thus where I use the method which uses the client I will have to handle only single EtcdException, not all of them.

What do you think about that guys?

**Comment by slintes** [comment]
I dont't think that would be a good idea:

1. The EtcdException is directly representing an error response of etcd, see it's public fields, and where it is instantiated. I guess it was on purpose that the default constructor was overwritten, so that you can't use the other constructors of Exception.

2. Even when the first point would not be there: I would prefer a more generic or a self created exception, which is related to your usecase. For example: if you use etcd for storing configuration data, then throw e.g. your own ConfigurationException. If you don't like to have your own exceptions, throw e.g. an IOException (because reading and writing configuration data is an I/O operation). This way the other parts of your application don't need to know anything about etcd and etcd4j, which is cleaner imho.

Just my 2 cents :)

**Comment by ghristov** [comment]
Well I think I might agree on the ConfigurationException. Btw is there a way to communicate without spamming here?

**Comment by slintes** [comment]
At least I don't know another way to communicate...

**Comment by jurmous** [comment]
Communicating through issues is I think the way Github works. It forces you to think which issues are open so it focusses on action. So you are welcome to open any questions/issues you encounter. If the project grows so big that user questions/issues in one store are too confusing I would probably add a link in the README for a new recommended place.

I agree with @slintes. EtcdExceptions should only be thrown by etcd itself so it keeps true to its original format and purpose. If you want to handle the exceptions on multiple places in your own code it is best to wrap the exceptions in your own defined exception. This way it is also easier to replace etcd4j with something different if something better comes up or if etcd4j changes the way exceptions work it is easier for you to adapt. 

@ghristov  It is also possible to "pipe" multiple types of exceptions to one catch block. 

```
try{
    promise.get();
} catch (IOException | EtcdException | TimeoutException e) {
    LOGGER.warn(e.getMessage());
}
```

But one thing that I didn't do and could possibly do is letting EtcdException extend IOException. It would save 1 catch in a generic try catch handler.  But it would make EtcdException a bit more hidden so you need to add it manually to a catch block. What are your thoughts?

**Comment by ghristov** [comment]
Ok agreed that EtcdException is ok like this. Actually I capture EtcdException,IOException, TimeoutException and throw ConfigurationException.

Regarding extending IOException... I think now is better. Like you said already, extending it you will hide information. Leave it that way. I will close this issue.

**Comment by jurmous** [comment]
:+1:
